server:
  port: 8081
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/ #服务注册到哪些Eureka Service
zuul:
  routes:
    user: 
      path: /user/**
      service-id: service-user